#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
xset r rate 250 35
pkill dunst
/usr/bin/dunst &

DUAL=`xrandr --listactivemonitors | grep HDMI-0`

if [[ -z "$DUAL" ]]
then
	bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 0
else 
	bspc monitor DP-0 -d 1 2 3 4 5 
	bspc monitor HDMI-0 -d 6 7 8 9 0
fi

bspc config border_width         4
bspc config window_gap          5

bspc config focused_border_color \#f1fcd5
bspc config normal_border_color \#283828
bspc config active_border_color \#283828

bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
#bspi_listen --config ~/.config/bspwm/bspi.ini &
